### PR TITLE
Update the public suffix list

### PR DESCRIPTION
**Pull request by tomhukins**

### CODE REVIEW

**Comment by xdg** [comment]
@rsimoes, would you mind shipping this to CPAN?  Or, if you're too busy, would you consider giving someone co-maintainer permission to ship it on your behalf? (I can't, but maybe Tom is willing.)  Thanks!

**Comment by rsimoes** [comment]
@xdg if someone agrees, I'll transfer ownership.

**Comment by xdg** [comment]
@tomhukins are you able to volunteer?

**Comment by tomhukins** [comment]
@rsimoes please see the email I sent to your cpan.org address on October 5th offering to do this.

**Comment by rsimoes** [comment]
@tomhukins @xdg transfer made!

**Pull request merged**
